from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter()

class ChatRequest(BaseModel):
    question: str


@router.post("/chat")
async def chat(request: ChatRequest):

    question = request.question.lower()

    # Greeting
    if any(word in question for word in ["hi", "hello", "hey"]):

        answer = "Hello! I am your AI Medical Assistant."

    # Confidence related questions
    elif "confidence" in question:

        # Low confidence
        if any(num in question for num in ["40", "45", "49", "50"]):

            answer = (
                "A confidence value around 40% to 50% means "
                "the AI model is uncertain about the prediction. "
                "The uploaded image may not be clear or the result "
                "needs further medical verification."
            )

        # Medium confidence
        elif any(num in question for num in ["60", "65", "70"]):

            answer = (
                "A confidence score around 60% to 70% indicates "
                "moderate certainty in the prediction."
            )

        # High confidence
        elif any(num in question for num in ["80", "85", "90", "95"]):

            answer = (
                "A confidence above 80% indicates the AI model "
                "is highly confident about the prediction result."
            )

        else:

            answer = (
                "Confidence percentage shows how certain "
                "the AI model is about its prediction."
            )

    # Symptoms
    elif any(word in question for word in ["symptoms", "symptom"]):

        answer = (
            "Common symptoms of heart disease include chest pain, "
            "shortness of breath, fatigue, dizziness, and irregular heartbeat."
        )

    # Effects
    elif any(word in question for word in ["effect", "affect"]):

        answer = (
            "Heart disease affects blood circulation and may "
            "lead to heart attack or stroke."
        )

    # Causes
    elif any(word in question for word in ["cause", "reason"]):

        answer = (
            "Heart disease may be caused by smoking, obesity, "
            "high blood pressure, stress, and diabetes."
        )

    # Prevention
    elif any(word in question for word in ["prevent", "prevention"]):

        answer = (
            "Regular exercise, healthy diet, and avoiding smoking "
            "help prevent heart disease."
        )

    # Treatment
    elif "treatment" in question:

        answer = (
            "Treatment may include medicines, healthy lifestyle changes, "
            "exercise, or surgery depending on the severity."
        )

    # Prediction meaning
    elif "prediction" in question:

        answer = (
            "Prediction result is generated by the AI model "
            "after analyzing the uploaded medical image."
        )

    # Heart disease general
    elif "heart disease" in question:

        answer = (
            "Heart disease refers to conditions affecting "
            "the heart and blood vessels."
        )

    else:

        answer = (
            "Sorry, I can answer only heart disease related questions."
        )

    return {
        "answer": answer
    }